name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Check lockfile sync
        run: pnpm install --frozen-lockfile

      - name: Install dependencies (fallback)
        if: failure()
        run: |
          echo "⚠️ Lockfile is out of sync. Installing anyway for now..."
          pnpm install --no-frozen-lockfile

      - name: Warn about lockfile mismatch
        run: |
          git diff --exit-code pnpm-lock.yaml || {
            echo "❌ pnpm-lock.yaml is not committed or out of sync with package.json. Please update and commit it.";
            exit 1;
          }

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Push Prisma schema to DB
        run: npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Check Vercel CLI version
        run: npx vercel --version
        working-directory: ./apps/web

      - name: Build frontend with Turbo
        run: pnpm turbo run build --filter=web

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v29
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/web
          vercel-args: --prod
